#!/usr/bin/env node
/**
 * AI Context Bundle generator (ADR 0043).
 *
 * Reads the one source of the architecture (`architecture/architecture.yaml` —
 * JSON syntax, valid YAML 1.2, so `JSON.parse` is all it takes) and assembles
 * the context a coding agent needs for one topic: the dependency rule for the
 * topic's packages, their layers, the relevant ADRs, flows, API docs and the
 * runnable examples — into `.ai/generated/<topic>-context.md`.
 *
 * Generated files are NOT committed (`.gitignore`): a committed bundle would be
 * a second, stale copy of the manifest. Regenerate instead.
 *
 * Usage:
 *   node tools/architecture/ai-context.mjs <topic>   (npm run ai:context <topic>)
 *   node tools/architecture/ai-context.mjs --list
 *   node tools/architecture/ai-context.mjs --changed [base]
 *     (npm run ai:context:changed) — the union of the bundles whose topics the
 *     changed files touch, written to `.ai/generated/changed-context.md`; the
 *     file→package→topic mapping is `tools/architecture/impact.mjs`'s, and this
 *     tool reuses it instead of owning a second copy (ADR 0043/0045).
 *
 * Exit codes: 0 = bundle written, 2 = usage error or unknown/broken topic
 * (so a typo never looks like a generated context).
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { analyzeImpact, filesToPackages, gitChangedFiles } from "./impact.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../..");
const MANIFEST = join(ROOT, "architecture", "architecture.yaml");
const OUTPUT_DIR = join(ROOT, ".ai", "generated");

/** Workspace roots, mirroring the `workspaces` field of the root manifest. */
const WORKSPACE_ROOTS = [
  { root: "packages", depth: 1 },
  { root: "packages", depth: 2 },
  { root: "tools", depth: 1 },
  { root: "apps", depth: 1 },
];

function fail(message) {
  process.stderr.write(`ai-context: ${message}\n`);
  process.exit(2);
}

/** Package name → workspace directory (for README links). */
function packageDirs() {
  const dirs = new Map();
  for (const { root: base, depth } of WORKSPACE_ROOTS) {
    const start = join(ROOT, base);
    if (!existsSync(start)) continue;
    const collect = (dir, level) => {
      const manifestPath = join(dir, "package.json");
      if (existsSync(manifestPath)) {
        try {
          const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
          if (manifest.name) dirs.set(manifest.name, relative(ROOT, dir));
        } catch {
          // A broken manifest is the checker's finding, not this tool's.
        }
        return;
      }
      if (level >= depth) return;
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (
          !entry.isDirectory() ||
          entry.name.startsWith(".") ||
          entry.name === "node_modules" ||
          entry.name === "dist"
        )
          continue;
        collect(join(dir, entry.name), level + 1);
      }
    };
    collect(start, 0);
  }
  return dirs;
}

/** ADR number ("0038") → file name in docs/adr (or undefined). */
function adrFiles() {
  const adrDir = join(ROOT, "docs", "adr");
  const files = new Map();
  for (const entry of readdirSync(adrDir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const match = entry.name.match(/^(\d{4})/);
    if (match) files.set(match[1], entry.name);
  }
  return files;
}

function repoPath(path) {
  return path.split("\\").join("/");
}

function bundle(topicName, manifest, dirs, adrs) {
  const topic = manifest.topics[topicName];
  const lines = [];
  lines.push(`# AI Context: ${topic.title}`);
  lines.push("");
  lines.push("> Generated by `tools/architecture/ai-context.mjs` from");
  lines.push("> [architecture/architecture.yaml](../../architecture/architecture.yaml).");
  lines.push("> **Do not edit, do not commit** (see `.gitignore`) — regenerate with");
  lines.push(`> \`npm run ai:context ${topicName}\`. The manifest is the source of truth`);
  lines.push("> (ADR 0031/0043); this file is a projection of it.");
  lines.push("");
  lines.push(`**${topic.summary}**`);
  lines.push("");

  lines.push("## Architecture rules (from the manifest)");
  lines.push("");
  lines.push("| Package | Layer | May import | Why (manifest) |");
  lines.push("|---|---|---|---|");
  for (const pkg of topic.packages) {
    const entry = manifest.packages[pkg];
    const layer = entry?.layer ?? "—";
    const may = (entry?.mayImport ?? []).length > 0 ? entry.mayImport.join(", ") : "nothing";
    lines.push(`| \`${pkg}\` | ${layer} | ${may} | ${entry?.why ?? ""} |`);
  }
  lines.push("");
  lines.push(
    "Every edge not listed in `May import` is forbidden; `npm run check:deps` fails on it. " +
      "Node builtins are only allowed in: " +
      (manifest.rules.nodeBuiltins.allowedIn.join(", ") ?? "—") +
      ". The UI is imported by nobody.",
  );
  lines.push("");

  lines.push("## Relevant packages");
  lines.push("");
  for (const pkg of topic.packages) {
    const dir = dirs.get(pkg);
    const readme =
      dir && existsSync(join(ROOT, dir, "README.md"))
        ? ` — [README](../../${repoPath(join(dir, "README.md"))})`
        : "";
    lines.push(`- \`${pkg}\` — Pfad: \`${dir ?? "unknown"}\`${readme}`);
  }
  lines.push("");

  lines.push("## ADRs");
  lines.push("");
  const missingAdrs = [];
  for (const adr of topic.adrs) {
    const file = adrs.get(adr);
    if (!file) missingAdrs.push(adr);
    else lines.push(`- [ADR ${adr}](../../docs/adr/${file})`);
  }
  lines.push("");

  lines.push("## API & flow docs");
  lines.push("");
  const docRefs = [
    ...(topic.docs ?? []).map((p) => ["API", p]),
    ...(topic.flows ?? []).map((p) => ["Flow", p]),
  ];
  const missingDocs = [];
  for (const [kind, path] of docRefs) {
    if (!existsSync(join(ROOT, path))) missingDocs.push(path);
    else lines.push(`- **${kind}:** [${path}](../../${path})`);
  }
  lines.push("");

  lines.push("## Runnable examples");
  lines.push("");
  const missingExamples = topic.examples ?? [];
  for (const path of missingExamples) {
    if (!existsSync(join(ROOT, path))) missingDocs.push(path);
    else lines.push(`- \`${path}\` — so wird diese API benutzt (läuft im Projekt \`integration\`)`);
  }
  if (missingExamples.length === 0) lines.push("- (keine für dieses Topic)");
  lines.push("");

  lines.push("## Invariants to keep");
  lines.push("");
  lines.push(
    "- The dependency graph above is a machine-checked rule (ADR 0031/0043): `npm run check:deps`.",
  );
  lines.push("- `package.json` must match the real imports (ADR 0042): `npm run check:manifests`.");
  lines.push(
    "- Missing evidence is a failure, not a warning (ADR 0033); evidence is assembled in exactly one place (ADR 0038).",
  );
  lines.push(
    "- Writes run staged through `WritePort` + `SafetyManager` only (ADR 0032, AGENTS 26).",
  );
  lines.push(
    "- Doc drift is a defect: manifest + ARCHITECTURE.md + affected READMEs + ADR change in one PR (AGENTS 34.24).",
  );
  lines.push("");
  lines.push("## Where to look next");
  lines.push("");
  lines.push("- Overall system: [ARCHITECTURE.md](../../ARCHITECTURE.md)");
  lines.push("- Task → place: [docs/code-map.md](../../docs/code-map.md)");
  lines.push("- Vocabulary: [docs/glossary.md](../../docs/glossary.md)");
  lines.push("- AI reading packs: [.ai/README.md](../README.md)");
  lines.push("");

  if (missingAdrs.length > 0)
    fail(`topic "${topicName}" references unknown ADRs: ${missingAdrs.join(", ")}`);
  if (missingDocs.length > 0)
    fail(`topic "${topicName}" references missing files: ${missingDocs.join(", ")}`);
  return lines.join("\n");
}

function main() {
  const argv = process.argv.slice(2);
  if (argv.length === 0 || argv[0] === "--help" || argv[0] === "-h") {
    process.stderr.write("usage: ai-context.mjs <topic> | --list | --changed [base]\n");
    process.exit(2);
  }

  if (!existsSync(MANIFEST)) fail(`manifest not found: ${repoPath(MANIFEST)}`);
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
  } catch (error) {
    fail(`manifest is not valid JSON (it must stay JSON-parseable, ADR 0002): ${error.message}`);
  }
  const topics = manifest.topics ?? {};

  if (argv[0] === "--list") {
    for (const [name, topic] of Object.entries(topics)) {
      process.stdout.write(`${name}\t${topic.title}\n`);
    }
    return;
  }

  if (argv[0] === "--changed") {
    const base = argv[1] ?? "HEAD";
    if (argv.length > 2) fail("usage: ai-context.mjs --changed [base]");
    let files;
    try {
      files = gitChangedFiles(base);
    } catch (error) {
      fail(error.message);
    }
    const dirs = packageDirs();
    const impact = analyzeImpact(manifest, dirs, filesToPackages(files, dirs).packages);
    const lines = [];
    lines.push(`# AI Context: changed files vs \`${base}\``);
    lines.push("");
    lines.push("> Generated by `tools/architecture/ai-context.mjs --changed` from");
    lines.push("> [architecture/architecture.yaml](../../architecture/architecture.yaml).");
    lines.push("> **Do not edit, do not commit** (see `.gitignore`) — regenerate with");
    lines.push("> `npm run ai:context:changed`. The file→package→topic mapping is");
    lines.push("> `tools/architecture/impact.mjs` (ADR 0043/0045); this file is a projection.");
    lines.push("");
    lines.push(`**Changed files:** ${files.length}` + (files.length === 0 ? " (clean tree)" : ""));
    lines.push("");
    for (const file of files) lines.push(`- \`${file}\``);
    lines.push("");
    lines.push(
      `**Seed packages:** ${impact.seeds.map((n) => `\`${n}\``).join(", ") || "—"}` +
        ` · **Affected (reverse \`mayImport\`):** ${impact.affected.map((e) => `\`${e.name}\``).join(", ") || "—"}`,
    );
    lines.push("");
    if (impact.topics.length === 0) {
      lines.push("No topic of the manifest covers a changed package — run");
      lines.push("`npm run ai:context --list` and pick a topic by hand if you still need context.");
    } else {
      lines.push(
        `Topics covered by these changes: ${impact.topics.map((t) => `\`${t}\``).join(", ")}.`,
      );
      lines.push("Their bundles follow, verbatim as `ai:context <topic>` writes them.");
    }
    const bundleText = lines.join("\n");
    const topicBundles = impact.topics.map(
      (topic) => `\n---\n\n${bundle(topic, manifest, dirs, adrFiles())}`,
    );
    mkdirSync(OUTPUT_DIR, { recursive: true });
    const outPath = join(OUTPUT_DIR, "changed-context.md");
    writeFileSync(outPath, `${bundleText}${topicBundles.join("")}`);
    process.stdout.write(`wrote ${repoPath(outPath)} (${impact.topics.length} topic bundles)\n`);
    return;
  }

  const topicName = argv[0];
  if (!topics[topicName]) {
    process.stderr.write(
      `unknown topic "${topicName}". Available: ${Object.keys(topics).join(", ")}\n`,
    );
    process.exit(2);
  }

  const bundleText = bundle(topicName, manifest, packageDirs(), adrFiles());
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const outPath = join(OUTPUT_DIR, `${topicName}-context.md`);
  writeFileSync(outPath, bundleText);
  process.stdout.write(`wrote ${repoPath(outPath)}\n`);
}

main();
