/**
 * Analysis service (AGENTS 22, 35).
 *
 * Owns the provider choice, builds the analysis input from a diagnostic session
 * and guarantees that AI output is always labelled with its source — the UI must
 * be able to show "generated by a local rule engine" vs "generated by a model".
 */

import { type Logger, createLogger } from "@vdp/shared";
import {
  AnalysisError,
  type AnalysisInput,
  type AnalysisProvider,
  type AnalysisResult,
} from "./types.js";

export interface AnalysisServiceOptions {
  providers?: readonly AnalysisProvider[];
  defaultProviderId?: string;
  logger?: Logger;
}

export interface AnalysisRequest {
  input: AnalysisInput;
  providerId?: string;
}

export class AnalysisService {
  private readonly providers = new Map<string, AnalysisProvider>();
  private readonly log: Logger;
  readonly history: AnalysisResult[] = [];

  constructor(private readonly options: AnalysisServiceOptions = {}) {
    for (const provider of options.providers ?? []) this.registerProvider(provider);
    this.log = (options.logger ?? createLogger("ai", { level: "INFO" })).child("ai");
  }

  registerProvider(provider: AnalysisProvider): void {
    this.providers.set(provider.id, provider);
  }

  listProviders(): Array<{ id: string; label: string; sendsDataOffBox: boolean }> {
    return Array.from(this.providers.values()).map((provider) => ({
      id: provider.id,
      label: provider.label,
      sendsDataOffBox: provider.sendsDataOffBox,
    }));
  }

  get defaultProviderId(): string | undefined {
    return this.options.defaultProviderId ?? Array.from(this.providers.keys())[0];
  }

  /** Run an analysis; every run is logged with its provider and result size. */
  async analyze(request: AnalysisRequest): Promise<AnalysisResult> {
    const providerId = request.providerId ?? this.defaultProviderId;
    if (!providerId) throw new AnalysisError("no analysis provider registered");
    const provider = this.providers.get(providerId);
    if (!provider)
      throw new AnalysisError(`unknown analysis provider "${providerId}"`, {
        known: Array.from(this.providers.keys()),
      });

    const started = Date.now();
    this.log.info("analysis started", {
      provider: providerId,
      offBox: provider.sendsDataOffBox,
      signals: request.input.signals.length,
      dtcs: request.input.dtcs.length,
    });
    try {
      const result = await provider.analyze(request.input);
      this.history.push(result);
      this.log.info("analysis finished", {
        provider: providerId,
        findings: result.findings.length,
        durationMs: Date.now() - started,
        source: result.source,
      });
      return result;
    } catch (error) {
      this.log.error("analysis failed", { provider: providerId, error: messageOf(error) });
      throw error;
    }
  }
}

function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
