/**
 * `npm run golden:record` — (re-)record the checked-in golden sessions.
 *
 * The fixtures in the repository are generated by this CLI, never edited by hand:
 * a golden file that was typed by a person is a wish, a recorded one is a fact.
 * Recording finishes with a verification run against the file it just wrote, so
 * the checked-in expectation is known to hold at the moment it is written.
 *
 * Output goes through `process.stdout`/`process.stderr` — the same convention the
 * workbench server uses. The tool's result is its *files*; the log lines are there
 * to be read by a human and by CI, and a `console` call would be indistinguishable
 * from a debug leftover.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { genericPackage } from "@vdp/definitions/generic";
import { createLogger } from "@vdp/shared";
import { goldenSessionToJson, parseGoldenSession, summariseChecks } from "./parse.js";
import { GENERIC_PACKAGE_NAME, STANDARD_RECIPES } from "./recipes.js";
import { recordGoldenSession } from "./record.js";
import { runGoldenSession } from "./run.js";

interface CliOptions {
  out: string;
  verify: boolean;
  only: string[];
}

const USAGE = "usage: golden-record [--out <dir>] [--verify] [--only <id>]";

function parseArgs(argv: readonly string[]): CliOptions {
  const options: CliOptions = { out: "tests/fixtures/golden-sessions", verify: false, only: [] };
  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index];
    if (arg === "--out") {
      const value = argv[++index];
      if (!value) throw new Error("--out needs a directory");
      options.out = value;
    } else if (arg === "--verify") {
      options.verify = true;
    } else if (arg === "--only") {
      const value = argv[++index];
      if (!value) throw new Error("--only needs an id");
      options.only.push(value);
    } else if (arg === "--help" || arg === "-h") {
      process.stdout.write(`${USAGE}\n`);
      process.exit(0);
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }
  return options;
}

function report(line: string): void {
  process.stdout.write(`${line}\n`);
}

function reportFailure(line: string): void {
  process.stderr.write(`${line}\n`);
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const logger = createLogger("golden-record", { level: "ERROR" });
  const version = genericPackage.version;
  const recipes = STANDARD_RECIPES.filter(
    (recipe) => options.only.length === 0 || options.only.includes(recipe.id),
  );
  if (recipes.length === 0) {
    throw new Error(`no recipe matched: ${options.only.join(", ")}`);
  }

  let failures = 0;
  for (const recipe of recipes) {
    const { session, observed } = await recordGoldenSession({
      recipe,
      definitions: genericPackage,
      definitionsName: GENERIC_PACKAGE_NAME,
      definitionsVersion: version,
      logger,
    });
    const file = resolve(options.out, `${recipe.id}.golden.json`);
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, goldenSessionToJson(session), "utf8");
    report(
      `recorded ${recipe.id}: ${observed.frames} frames, ${observed.ecus} ECUs, ` +
        `${observed.dtcs} DTCs, ${observed.signals} signal expectations`,
    );

    if (options.verify) {
      const parsed = parseGoldenSession(await readFile(file, "utf8"), recipe.id);
      const result = await runGoldenSession(parsed, { definitions: genericPackage, logger });
      report(`verified ${recipe.id}: ${summariseChecks(result.checks)}`);
      for (const check of result.checks.filter((entry) => !entry.ok)) {
        failures++;
        reportFailure(`  FAIL ${check.name}: expected ${check.expected}, got ${check.actual}`);
      }
    }
  }

  if (failures > 0) {
    reportFailure(
      `${failures} check(s) failed — the expectation does not hold against its own recording`,
    );
    process.exit(1);
  }
}

await main();
