/**
 * Golden sessions (master backlog P0 #10).
 *
 * Every checked-in recording is played back through the full pipeline — replay
 * transport, ISO-TP, UDS client, definitions, decoding — and must still produce the
 * ECUs, fault codes and signal values it produced when it was recorded. This is the
 * test that turns "it worked on the bench" into "it still works", and it is the
 * reason a protocol change now has to face the practice instead of the reviewer.
 *
 * The fixtures themselves live in `tests/fixtures/golden-sessions/` and are
 * generated by `npm run golden:record`; the recipes they come from are in
 * `tools/golden-sessions/src/recipes.ts`. They are never edited by hand.
 */

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { genericPackage } from "@vdp/definitions/generic";
import {
  findVinLikeTokens,
  parseGoldenSession,
  runGoldenSession,
  STANDARD_RECIPES,
  summariseChecks,
} from "@vdp/golden-sessions";
import { createLogger } from "@vdp/shared";
import { describe, test } from "vitest";

const logger = createLogger("replay", { level: "ERROR" });
const FIXTURE_DIR = "tests/fixtures/golden-sessions";

function fixturePath(id: string): string {
  return join(FIXTURE_DIR, `${id}.golden.json`);
}

describe("golden sessions", () => {
  for (const recipe of STANDARD_RECIPES) {
    test(`${recipe.id}: the expectation still holds against its own recording`, async () => {
      const session = parseGoldenSession(await readFile(fixturePath(recipe.id), "utf8"), recipe.id);
      const result = await runGoldenSession(session, { definitions: genericPackage, logger });

      const failed = result.checks.filter((check) => !check.ok);
      assert.deepEqual(
        failed.map((check) => `${check.name} (expected ${check.expected}, got ${check.actual})`),
        [],
        `${recipe.id} regressed — ${summariseChecks(result.checks)}. Re-record with npm run golden:record once the change is intended.`,
      );
      assert.ok(
        result.checks.length >= 10,
        "a golden run compares ECUs, codes, signals and the replay",
      );
      assert.equal(result.ok, true);
    });
  }

  test("every fixture names the definition package and version it was recorded from", async () => {
    for (const recipe of STANDARD_RECIPES) {
      const session = parseGoldenSession(await readFile(fixturePath(recipe.id), "utf8"), recipe.id);
      assert.equal(session.provenance.definitions.package, "generic");
      assert.equal(
        session.provenance.definitions.version,
        genericPackage.version,
        `${recipe.id} was recorded against another definition version — re-record it`,
      );
      assert.equal(session.provenance.redaction.includes("vin"), true);
      assert.equal(
        session.recording.format,
        "vdp.session",
        "the raw session export is the evidence; a decoded summary would hide the frames",
      );
    }
  });

  test("no fixture contains a VIN that is not a placeholder", async () => {
    for (const recipe of STANDARD_RECIPES) {
      const json = await readFile(fixturePath(recipe.id), "utf8");
      // The recording is the part that can leak: the expectations are written by the
      // recorder, the frames come from the vehicle.
      const session = parseGoldenSession(json, recipe.id);
      assert.deepEqual(
        findVinLikeTokens(JSON.stringify(session.recording)),
        [],
        `${recipe.id} still carries a VIN-shaped token in its frames`,
      );
      assert.equal(
        session.expectations.identity?.vin,
        "REDACTED-VIN-0000",
        `${recipe.id} must reference the placeholder, not a real number`,
      );
    }
  });
});
