/**
 * Generic (manufacturer independent) definition package.
 *
 * Signal semantics are taken from the publicly standardized OBD-II PID set
 * (SAE J1979 / ISO 15031-5) and mapped onto the conventional UDS DID range
 * 0xF4xx (DID = 0xF400 + PID). Identification DIDs use the standardized
 * ISO 14229-1 values (0xF18x/0xF19x).
 *
 * Nothing here is copied from a commercial product's database (AGENTS 24).
 */

import type { DefinitionPackage } from '../schema.js';

export const genericPackage: DefinitionPackage = {
  schemaVersion: 1,
  oem: 'generic',
  name: 'Generic UDS / OBD-II baseline',
  version: '1.0.0',
  provenance: {
    sourceType: 'standard',
    source: 'SAE J1979 / ISO 15031-5 PID semantics, ISO 14229-1 identification DIDs — own encoding, no third-party database used',
    version: '1.0.0',
    notes: 'DID mapping 0xF400 + PID is the conventional UDS mapping of Mode 01 PIDs.',
  },
  ecus: [
    {
      id: 'engine',
      name: 'Engine Control Unit',
      protocol: 'uds',
      address: { txId: 0x7e0, rxId: 0x7e8, functionalId: 0x7df },
      timing: { p2Ms: 50, p2StarMs: 5000 },
      identification: [
        { label: 'VIN', did: 0xf190, encoding: 'ascii' },
        { label: 'Spare part number', did: 0xf187, encoding: 'ascii' },
        { label: 'Application software', did: 0xf181, encoding: 'ascii' },
        { label: 'ECU serial number', did: 0xf18c, encoding: 'ascii' },
      ],
      dtcs: [
        {
          code: 'P0420',
          description: 'Catalyst system efficiency below threshold (bank 1)',
          severity: 'major',
          hint: 'Compare upstream/downstream lambda sensor activity and check exhaust leaks before condemning the catalyst.',
          relatedSignals: ['engine.short_term_fuel_trim', 'engine.long_term_fuel_trim', 'engine.load', 'engine.intake_air_temperature'],
          // Snapshot record of this package: engine speed, load, coolant
          // temperature and vehicle speed — the operating point the fault was
          // stored at. The layout is declared, never guessed (AGENTS 13/20).
          freezeFrame: [
            { did: 0xf40c, name: 'Engine speed', signals: ['engine.rpm'] },
            { did: 0xf404, name: 'Calculated load', signals: ['engine.load'] },
            { did: 0xf405, name: 'Coolant temperature', signals: ['engine.coolant_temperature'] },
            { did: 0xf40d, name: 'Vehicle speed', signals: ['vehicle.speed'] },
          ],
        },
        {
          code: 'P0300',
          description: 'Random/multiple cylinder misfire detected',
          severity: 'critical',
          hint: 'Check ignition components and fuel trims; freeze frame RPM/load narrows the operating point down.',
          relatedSignals: ['engine.rpm', 'engine.load', 'engine.timing_advance', 'engine.short_term_fuel_trim'],
          freezeFrame: [
            { did: 0xf40c, name: 'Engine speed', signals: ['engine.rpm'] },
            { did: 0xf404, name: 'Calculated load', signals: ['engine.load'] },
            { did: 0xf40d, name: 'Vehicle speed', signals: ['vehicle.speed'] },
          ],
        },
        {
          code: 'P0171',
          description: 'System too lean (bank 1)',
          severity: 'major',
          hint: 'Look for unmetered air, fuel pressure or MAF issues; correlate with long term fuel trim.',
          relatedSignals: ['engine.long_term_fuel_trim', 'engine.short_term_fuel_trim', 'engine.maf_airflow', 'engine.intake_manifold_pressure'],
          freezeFrame: [
            { did: 0xf40c, name: 'Engine speed', signals: ['engine.rpm'] },
            { did: 0xf405, name: 'Coolant temperature', signals: ['engine.coolant_temperature'] },
          ],
        },
      ],
      description: 'Engine control unit reachable via standard OBD identifiers.',
    },
    {
      id: 'transmission',
      name: 'Transmission Control Unit',
      protocol: 'uds',
      address: { txId: 0x7e1, rxId: 0x7e9, functionalId: 0x7df },
      identification: [
        { label: 'VIN', did: 0xf190, encoding: 'ascii' },
        { label: 'ECU serial number', did: 0xf18c, encoding: 'ascii' },
      ],
      dtcs: [
        { code: 'P0700', description: 'Transmission control system malfunction', severity: 'major' },
        { code: 'P0715', description: 'Input/turbine speed sensor circuit malfunction', severity: 'minor' },
      ],
    },
    {
      id: 'abs',
      name: 'ABS / Brake Control Unit',
      protocol: 'uds',
      address: { txId: 0x713, rxId: 0x77b, functionalId: 0x7df },
      identification: [
        { label: 'VIN', did: 0xf190, encoding: 'ascii' },
        { label: 'Hardware version', did: 0xf193, encoding: 'ascii' },
      ],
      dtcs: [
        { code: 'C0035', description: 'Left front wheel speed sensor circuit', severity: 'major' },
        { code: 'U0121', description: 'Lost communication with anti-lock brake system control module', severity: 'critical' },
      ],
    },
  ],
  signals: [
    // --- identification -------------------------------------------------
    {
      id: 'engine.vin',
      name: 'Vehicle Identification Number',
      ecu: 'engine',
      did: 0xf190,
      byteOffset: 0,
      length: 17,
      encoding: 'ascii',
      description: 'ISO 3779 vehicle identifier.',
    },
    {
      id: 'engine.spare_part_number',
      name: 'Spare part number',
      ecu: 'engine',
      did: 0xf187,
      byteOffset: 0,
      length: 16,
      encoding: 'ascii',
    },
    {
      id: 'engine.application_software',
      name: 'Application software identification',
      ecu: 'engine',
      did: 0xf181,
      byteOffset: 0,
      length: 16,
      encoding: 'ascii',
    },
    {
      id: 'engine.serial_number',
      name: 'ECU serial number',
      ecu: 'engine',
      did: 0xf18c,
      byteOffset: 0,
      length: 16,
      encoding: 'ascii',
    },

    // --- live measurements (PID semantics, DID = 0xF400 + PID) ----------
    {
      id: 'engine.rpm',
      name: 'Engine speed',
      ecu: 'engine',
      did: 0xf40c,
      byteOffset: 0,
      length: 2,
      encoding: 'uint16',
      scale: 0.25,
      unit: 'rpm',
      min: 0,
      max: 16383.75,
      critical: true,
      description: 'PID 0x0C — 0.25 rpm per bit.',
    },
    {
      id: 'engine.coolant_temperature',
      name: 'Engine coolant temperature',
      ecu: 'engine',
      did: 0xf405,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      offsetValue: -40,
      unit: '°C',
      min: -40,
      max: 215,
      critical: true,
      description: 'PID 0x05.',
    },
    {
      id: 'engine.load',
      name: 'Calculated engine load',
      ecu: 'engine',
      did: 0xf404,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      scale: 0.39215686274509803,
      unit: '%',
      min: 0,
      max: 100,
      description: 'PID 0x04 — 100/255 %.',
    },
    {
      id: 'vehicle.speed',
      name: 'Vehicle speed',
      ecu: 'engine',
      did: 0xf40d,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      unit: 'km/h',
      min: 0,
      max: 255,
      critical: true,
      description: 'PID 0x0D.',
    },
    {
      id: 'engine.intake_air_temperature',
      name: 'Intake air temperature',
      ecu: 'engine',
      did: 0xf40f,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      offsetValue: -40,
      unit: '°C',
      description: 'PID 0x0F.',
    },
    {
      id: 'engine.throttle_position',
      name: 'Throttle position',
      ecu: 'engine',
      did: 0xf411,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      scale: 0.39215686274509803,
      unit: '%',
      min: 0,
      max: 100,
      description: 'PID 0x11.',
    },
    {
      id: 'engine.short_term_fuel_trim',
      name: 'Short term fuel trim (bank 1)',
      ecu: 'engine',
      did: 0xf406,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      scale: 0.78125,
      offsetValue: -100,
      unit: '%',
      min: -100,
      max: 99.2,
      critical: true,
      description: 'PID 0x06 — 100/128 % per bit, offset -100 %.',
    },
    {
      id: 'engine.long_term_fuel_trim',
      name: 'Long term fuel trim (bank 1)',
      ecu: 'engine',
      did: 0xf407,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      scale: 0.78125,
      offsetValue: -100,
      unit: '%',
      min: -100,
      max: 99.2,
      critical: true,
      description: 'PID 0x07.',
    },
    {
      id: 'engine.intake_manifold_pressure',
      name: 'Intake manifold absolute pressure',
      ecu: 'engine',
      did: 0xf40b,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      unit: 'kPa',
      min: 0,
      max: 255,
      description: 'PID 0x0B.',
    },
    {
      id: 'engine.timing_advance',
      name: 'Ignition timing advance',
      ecu: 'engine',
      did: 0xf40e,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      scale: 0.5,
      offsetValue: -64,
      unit: '°',
      description: 'PID 0x0E.',
    },
    {
      id: 'engine.maf_airflow',
      name: 'MAF air flow rate',
      ecu: 'engine',
      did: 0xf410,
      byteOffset: 0,
      length: 2,
      encoding: 'uint16',
      scale: 0.01,
      unit: 'g/s',
      min: 0,
      max: 655.35,
      description: 'PID 0x10.',
    },
    {
      id: 'engine.fuel_rail_pressure',
      name: 'Fuel rail pressure (manifold vacuum relative)',
      ecu: 'engine',
      did: 0xf423,
      byteOffset: 0,
      length: 2,
      encoding: 'uint16',
      scale: 10,
      unit: 'kPa',
      description: 'PID 0x23.',
    },
    {
      id: 'engine.runtime',
      name: 'Run time since engine start',
      ecu: 'engine',
      did: 0xf41f,
      byteOffset: 0,
      length: 2,
      encoding: 'uint16',
      unit: 's',
      description: 'PID 0x1F.',
    },
    {
      id: 'engine.fuel_system_status',
      name: 'Fuel system status',
      ecu: 'engine',
      did: 0xf403,
      byteOffset: 0,
      length: 1,
      encoding: 'bitmask',
      enumMapping: {
        1: 'openLoopInsufficientTemp',
        2: 'closedLoop',
        4: 'openLoopDrivingConditions',
        8: 'openLoopSystemFailure',
        16: 'closedLoopFault',
      },
      description: 'PID 0x03.',
    },

    // --- transmission ---------------------------------------------------
    {
      id: 'transmission.oil_temperature',
      name: 'Transmission oil temperature',
      ecu: 'transmission',
      did: 0xf405,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      offsetValue: -40,
      unit: '°C',
    },
    {
      id: 'transmission.gear_position',
      name: 'Selected gear position',
      ecu: 'transmission',
      did: 0xf4a4,
      byteOffset: 0,
      length: 1,
      encoding: 'uint8',
      enumMapping: { 0: 'park', 1: 'reverse', 2: 'neutral', 3: 'drive', 4: 'sport' },
    },

    // --- ABS ------------------------------------------------------------
    {
      id: 'abs.wheel_speed_front_left',
      name: 'Wheel speed front left',
      ecu: 'abs',
      did: 0xf40d,
      byteOffset: 0,
      length: 2,
      encoding: 'uint16',
      scale: 0.01,
      unit: 'km/h',
      critical: true,
    },
    {
      id: 'abs.wheel_speed_front_right',
      name: 'Wheel speed front right',
      ecu: 'abs',
      did: 0xf40d,
      byteOffset: 2,
      length: 2,
      encoding: 'uint16',
      scale: 0.01,
      unit: 'km/h',
      critical: true,
    },
    {
      id: 'abs.brake_pedal',
      name: 'Brake pedal switch',
      ecu: 'abs',
      did: 0xf411,
      byteOffset: 0,
      length: 1,
      encoding: 'bitmask',
      bitOffset: 0,
      bitLength: 1,
      enumMapping: { 0: 'released', 1: 'pressed' },
    },
  ],
};
